on:
 push : 
   branches:
      - dev
name: deploy plataforma  psicomob via  on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER_TESTE }}
        username: ${{ secrets.FTP_USERNAME_TESTE}}
        password: ${{ secrets.FTP_PASSWORD_TESTE }}
        server-dir: psicomob/